### ISSUE TITLE
Psionics are broken

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#120]
All the skill base formula I had input are all gone.
I cannot drag & drop psionics on an actor

**Comment by scooper4711** [comment]
Seems to only impact existing items. Test game with no data migration works ok.

**Comment by scooper4711** [comment]
```
Foundry VTT | Created OwnedItem u7Ela5z8sGcW4hIv in parent Actor YcNv4SNS35267oXn foundry.js:4503 
Foundry VTT | Rendering HarnMasterItemSheet log.js:33
```

**Comment by scooper4711** [comment]
vs. what it looks like when it works:
```
Foundry VTT | Deleted OwnedItem Xwrq5eYVqU7wnmIj from parent Actor KM34CGNvRad0ZVUS foundry.js:29832 
Foundry VTT | Created OwnedItem fSu4iuSwh068ETCo in parent Actor KM34CGNvRad0ZVUS foundry.js:4503 
Foundry VTT | Rendering HarnMasterItemSheet
```

**Comment by toastygm** [comment]
As you suspected, this is a data migration bug.  I can fix the bug, but you would have to re-perform data migration.  Since this does not seem to be a problem for many people, I would suggest one of two things:
1. If you did a lot of data entry for psionic talents, move all of the psionic talents into a compendium pack and send me the *.db file.  I can manually massage it into the correct format.
2. If there is not too much data entry, then re-enter the talents by hand.
This is yet another reason why I am so hesitant about doing data migrations.
