### ISSUE TITLE
Missile Combat:  range EML modifiers

### ISSUE THREAD

**Issue by mrg67** [toastygm/HarnMaster-3-FoundryVTT#157]
Are the negative modifiers (Medium -20, Long -40, Extreme -80) supposed to automatically be applied in the AML for missile attacks?  They don't appear to be, from the Chat display.

Actor is throwing a shorkana at medium range, but the AML is still 45, when their current EML is also 45.

![image](https://user-images.githubusercontent.com/74210758/101949343-5023cc80-3ba8-11eb-8697-df34f5f4af87.png)

**Comment by toastygm** [comment]
No, currently all AML modifiers must be input by the user.  I did this to allow GMs more flexibility in applying modifiers.  That said, in comments since then it has been suggested that I account for the standard modifiers, and then allow the GM to provide an ADDITIONAL modifier to override those if they wish.  That will probably be provided in a future enhancement.  For now, apply all modifiers yourself for range.

**Comment by scooper4711** [comment]
One thing we discussed was to prepopulate the modifier with the range modifier. 
Eg if the range results in a modifier of -10, that is already populated in the field. And the the GM can say something else if desired.
