### ISSUE TITLE
enhancement: unify the description

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#162]
The FFF compendium has the original all-text descriptions of the people.
New actors get the new (suggested by me) table-based layout.
Looking at how the actor sheet re-sizes with the table, it may not be the best solution.
Here are two screenshots of the same FFF character. 
One has the table, the other the old text version. The first few attributes in the text version I've bolded the header text.

Advantages of table: easier to read (IMO). Looks cooler (IMO)
Advantages of text only: more compact. Resizes better with current actor sheet.

I think we should choose one format and get new actors and the FFF to use the same one.
<img width="574" alt="Screen Shot 2020-12-12 at 5 42 53 PM" src="https://user-images.githubusercontent.com/1970249/102000314-842fe800-3ca3-11eb-859a-8ce5db6403a9.png">
<img width="514" alt="Screen Shot 2020-12-12 at 5 45 14 PM" src="https://user-images.githubusercontent.com/1970249/102000316-87c36f00-3ca3-11eb-95fa-4e204836c5ae.png">

**Comment by scooper4711** [comment]
By playing with the table, I was able to make it look better.
I set the width to 99%, and all the cells to 50%. I removed the border.
It still takes up more space, but looks better than the default table. The issue is of course that as soon as you happen to click on the middle bar while editing, the percentage widths get replaced with absolute widths.
<img width="526" alt="Screen Shot 2020-12-12 at 6 08 45 PM" src="https://user-images.githubusercontent.com/1970249/102000502-5fd50b00-3ca5-11eb-8390-b686352035f9.png">

So I guess another advantage with the text only approach (with bolded text) is that it looks better with less effort to maintain. :/

**Comment by toastygm** [comment]
There is going to be a significant amount of work in order to do something that has relatively minor impact.  You will need to read in all of the characters in the pack, find the description, then parse the description looking for lines.  On each line, you will need to detect all text from the beginning of the line to the first colon, then replace that text with the same text but between <strong> elements.  Then, resave all of the entries in the pack.  And hope you haven't broken anything.

If someone else wants to take the effort to write the code to do this and make that change, that would be fine.  But I'm not going to make this change.

In any case, this is the wrong place for this request.  This belongs in the FFF module issues list.  I'm closing this issue.

**Comment by scooper4711** [comment]
rather than open a new request elsewhere, I'll just post my sed script which converts the html in the db file to the text-only, but bolded version:
```s,<p>Apparent Age:,<p><strong>Apparent Age:</strong>,g 
s,\\nCulture:,<strong>Culture:</strong>,g
s,\\nSocial Class:,<strong>Social Class:</strong>,g
s,\\nHeight:,<strong>Height:</strong>,g
s,\\nFrame:,<strong>Frame</strong>:,g
s,\\nWeight:,<strong>Weight:</strong>,g
s,\\nAppearance:,<strong>Appearance:</strong>,g
s,\\nHair Colour:,<strong>Hair Colour:</strong>,g
s,\\nEye Colour:,<strong>Eye Colour:</strong>,g
s,\\nVoice:,<strong>Voice:</strong>,g
s,\\nObvious Medical Traits:,<strong>Obvious Medical Traits:</strong>,g
s,\\nApparent Occupation:,<strong>Apparent Occupation:</strong>,g
s,\\nApparent Wealth:,<strong>Apparent Wealth:</strong>,g
s,\\nWeapons:,<strong>Weapons:</strong>,g
s,\\nArmour,<strong>Armour</strong>,g
s,\\nCompanions:,<strong>Companions:</strong>,g
s,\\nOther obvious features,<strong>Other obvious features</strong>,g
```
Here's the command to run:
```
sed -f convert.sed friends-foes-and-followers-v1.orig > friends-foes-and-followers-v1.db 
```
I have my compendium in the format I want. We can keep this closed.
