### ISSUE TITLE
Enhancement: add description for Std Skill Condition

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#165]
The skill Condition impacts how the game engine performs certain calculations.
These should be in the description or note for the skill.

**Comment by toastygm** [comment]
I don't think I agree.  The condition skill works **exactly** as specified in the manual: if it is present, it is used to calculate endurance, otherwise the rules for calculating endurance in the rulebook applies.  I don't think any additional instructions are necessary (other than to maybe indicate that I in fact follow the rules for Condition).
