### ISSUE TITLE
bug: equipping a weapon before you have the skill sets the skill to none

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#169]
wasn't going to open this bug, but shields behave differently.
If you add a weapon before you add the skill for the weapon - e.g. broadsword and sword skill or dagger and dagger skill - then the weapon's associated skill gets set to None and the AML is zero.

This doesn't appear to be the case with shields. I added a roundshield and then added the shield skill, and once I set the EML for the shield skill, the roundshield DML updated automatically.

**Comment by toastygm** [comment]
This is not a bug.  It may be inconsistent behavior between shields and the weapons, but if you add a weapon before the skill the weapon associated skill will set to "None".  I'm not certain why the shields fix themselves, but that is not a guaranteed behavior, and I don't consider this a bug.

The correct approach is to add the skill first, then add the weapon.  Otherwise, you will have to go back and manually set the associated skill for the weapon.
