### ISSUE TITLE
bug: legacy macros for AML rolls work off selected, not targeted

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#171]
the legacy macros for AML require that I select my target, not target him.

**Comment by toastygm** [comment]
I'm not sure I understand.  The legacy macros do not have any concept of who the target is.  They only make an AML roll based on AML of the **attacker's** weapon.  You should never "target" anything.

Now, the question does arise how do you know who the actor is who is performing a macro?  In this case, you are choosing the "source".  Because the old macros do not have any concept of combat, the only way is to actually select a token.

So, this is correct behavior.
