### ISSUE TITLE
bug: AQ isn't displayed on combat tab

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#172]
I gave my actor AQ 10 on all his armor. 
The AQ column on the combat tab shows an AQ of 0 for all locations.

**Comment by toastygm** [comment]
It turns out this was an error; I should never have placed AQ in that location at all.  An armor location is often composed of many layers of armor, each of which has its own AQ.  If you are wearing a Tunic and Leggings, your hips are covered with two layers of armor, each of which might have different AQ.  So what is the AQ of that location?  That doesn't make sense.

I'm leaving the AQ field on the armor, but I'm removing it from the location.
