### ISSUE TITLE
Two containers with the same name confuse the dropdown

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#203]
If an actor has two containers with the same name, e.g. purse, silk, then when editing an individual item, the drop-down for which container it is in lists only one.

**Comment by toastygm** [comment]
Then don't do that! Ensure you always use unique names for containers.

**Comment by scooper4711** [comment]
I thought you switched to using UUID?

**Comment by toastygm** [comment]
This will not be changed.  The solution is for the user to not specify two containers with the same name.  Internally, the system is correctly tracking the container, it is just that since the user has named them identically, the user can't distinguish between them in the dropdown.

The solution is for the user to change the name of one of the containers so it is unique; then the names in the dropdown will be unique and there will be no difficulty for the user.
