### ISSUE TITLE
Convocational Icons for spells can ignore convocation based on test in the spell name

### ISSUE THREAD

**Issue by Slithkanter** [toastygm/HarnMaster-3-FoundryVTT#226]
This is a strange one.  

1. On the Esoterics tab of the character sheet, click +Add to add a new spell.
2. For the name of the spell enter in Shield of Kail (Don't laugh, this is an official spell source: Spellpack 7 Neutral HM3.pdf)
3. Click Create
4. Note that the icon for the spell is a shield.
5. On the Convocation drop down box select Neutral.  Note that the shield icon does not change to the pentagram icon associated with the Neutral convocation.
6. And the shield icon is sticky, meaning I can't change it.
[spell_icon_display_issue.pdf](https://github.com/toastygm/HarnMaster-3-FoundryVTT/files/5891768/spell_icon_display_issue.pdf)

**Comment by toastygm** [comment]
Well, this isn't so much a "bug" as a "feature". :)

Throughout the system, wherever there is an icon I use a consistent
function to set the icon based on the **name** of the item.  Since your
spell has the word "Shield" in it, and the heristic recognizes that word,
it automatically sets the icon to a shield.  Changing the convocation will
have no effect, it is based on the name.

That said, this renaming occurs only when there is a "default" icon.  If
you click on the icon and set it manually to the Neutral convocation icon,
it will stay that way.

Similarly, if you had a spell called "Sword of Hrothgar", the icon would
become a sword icon, even if the convocation was Peleahn.

--
*Tom Rodriguez*
*w:* www.casualinsight.com | *e:* tmrodrig@gmail.com
*LinkedIn:* www.linkedin.com/in/tomrodriguez
*Twitter:* @TomRodriguezCI <https://twitter.com/TomRodriguezCI>

**Comment by Slithkanter** [comment]
So can you change the icon back to the correct Neutral convocation icon?  I tried that and it does not seem to stick, reverting back to the shield each time.

**Comment by toastygm** [comment]
The logic for automatically determining the icon was very convoluted; I was trying to be "smart" about parsing the names to figure out what icon to use.  That seems to have ultimately been a bad idea.

My new approach is to only set the icon once, when the item is created.  After that, it is never changed again, regardless of name changes, convocation changes, etc.  So, after the item has been created, any further updates of the icon will have to be manually done.  This will be much more intuitive, and won't suffer from "undoing" any changes you want to make.

Expect this new behavior to show up in 1.2.8 and later.
