### ISSUE TITLE
Gold Mode: Endur. in Combat Tab calulated as HM3

### ISSUE THREAD

**Issue by TimoLemburg** [toastygm/HarnMaster-3-FoundryVTT#256]
On the Character Sheet on the Combat Tab the Endur. field still gets calculated as in HM3. In HMG there is an attribute that should be referenced.

**Comment by toastygm** [comment]
Think of the Endurance field in the Combat tab as "Effective Endurance".  When the CONDITION skill is present (always true for HMG), then this is always calculated as CONDITION / 5 rounded to nearest whole number.  In HM3, this is further modified by PP, but in HMG I make no such modification.

This is a useful number to know, both in HMG and HM3, because I use it for all endurance calculations, and there is nowhere else to see it without showing it here.

Therefore this is not a bug, and is working as designed.

If you disagree, please reopen this and provide further comment.
