### ISSUE TITLE
Armor entered in Gear not appearing in Combat for creatures

### ISSUE THREAD

**Issue by DustyGold** [toastygm/HarnMaster-3-FoundryVTT#267]
![gargun armor 1](https://user-images.githubusercontent.com/86576601/123979423-b4647d00-d98e-11eb-86a2-b11b2eec4873.jpg)
![gargun armor 2](https://user-images.githubusercontent.com/86576601/123979450-bb8b8b00-d98e-11eb-9a48-55890316d741.jpg)

I'm including screen caps of the gear and combat for creatures. While this is for gargun, it happens with all creatures - armor doesn't appear on the combat page. I'm not sure if that's me issue or an issue with the code, so I'm submitting it here. My apologies if this isn't an issue.

**Comment by scooper4711** [comment]
This is by design. 
For humanoids that wear armor, use an actor. 

Creatures are meant for non humanoids without armor/standard hit locations. There you set the armor in the armor location.

**Comment by toastygm** [comment]
So here's the issue: you need to FIRST create the Armor locations.  THEN, you enter the armor.  If a piece of armor has a location that matches an existing "Armor Location", then that armor will be applied to that "Armor Location".

So, for example, a Tunic has the following locations defined: Upper Arm, Shoulder, Thorax, Abdomen, Hip, Groin.  On a humanoid, the "Right Upper Arm" has a "Hit Location" of "Upper Arm".  See the picture:
<img width="559" alt="Screen Shot 2021-06-30 at 10 18 39 AM" src="https://user-images.githubusercontent.com/73371093/124004326-bc232200-d98c-11eb-9df0-4f4639c0e324.png">

When the Location on the armor matches the Location Type on the Armor Location, it then applies the armor values to that Armor Location.

Because creatures have such a wide variety of armor locations, armor calculation does not work for "Creature" sheets, only for "Character" sheets.  This is by design.  For creatures, you must enter in the armor values manually for each location.

**Comment by DustyGold** [comment]
Thank you. I suspected it was a "me" thing.
