### ISSUE TITLE
Feature request: move.effective as a default bar attribute

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#276]
When moving a character in combat, it would be nice to be able to see how far they can move without having to open the token sheet. This can be accomplished by going in to a token or prototype token and setting bar2 to move.effective. However, this must be done for each actor.

Similar to how you made the calculated shockIndex value something which can be selected in Default Token Configuration, make move.effective a selectable attribute.

Yes, I know it's a hack. You can assign this a low prio.

**Comment by toastygm** [comment]
Not possible without a data model change.

All of the "effective" values, including "move.effective", are ephemeral
(calculated) values, and are not strictly part of the data model.  Because
they don't exist in the data model, FVTT does not include them in that
token configuration dropdown.  In order to get them to show up there, I
would have to add them to the data model, which would mean a data model
change.

The reason shockIndex works is because I include shockIndex as a default
attribute bar attribute in the system.json file.  But that is not flexible;
I can't define a variety of items there.  I am certain that virtually
everyone will want to track ShockIndex, so putting it there made sense.

This is unlikely to be something I actually will implement.
