### ISSUE TITLE
Active Effects Skill EML Multiplier does not round to whole numbers

### ISSUE THREAD

**Issue by jpmcdonald** [toastygm/HarnMaster-3-FoundryVTT#302]
When applying a multiplier to a skill through an Active Effect, non-whole numbers can result.  e.g. an ML of 61 when multiplied by 0.5 results in and ML of 30.5; this should be rounded to the nearest whole number or 30.

**Comment by toastygm** [comment]
Should this be "round to nearest whole number", or "round down to nearest
whole number"?

Your example suggests rounding down, since the nearest whole number to 30.5
is 31.

**Comment by jpmcdonald** [comment]
Introduction 2:  Rounding of Fractions: Except where otherwise indicated, fractions
should be rounded to the nearest whole number.

Sorry for the confusion. Yes, that's the rule they teach now... As an engineer/statistician if I round in that manner it introduces bias in a table of numbers.  I was always taught when you are rounding at exactly .5 round down if even and up if odd.  Thus 30.5 rounds to 30. and 31.5 rounds to 32.  

I don't think this special case matters at all in this case so yes, I mean round to the nearest whole number.

**Comment by toastygm** [comment]
I'm just using Math.round() man, whatever it does! :)

**Comment by toastygm** [comment]
So far as I can tell, I am actually performing rounding at `HarnMasterActor#_setupEffectiveAbilities` (actor.js:543).  An example of the code is:

```javascript
        data.abilities.strength.effective = Math.max(Math.round(eph.strength + Number.EPSILON) - data.physicalPenalty, 0);
```

As you can see, I am using `Math.round()` in order to round these values to the nearest whole number. (In previous steps I have already ensured that `data.physicalPenalty` is a whole number.)

The reason for the `Math.EPSILON` is that due to issues with internal representations of floating point numbers, it is possible to have numbers such as 1.4999999999999 instead of 1.5 during some floating point calculations.  This is obviously supposed to be 1.5, so the answer is to add the smallest possible floating point value to the number, which should be enough to "Kick it over the line" and ensure it rounds correctly.  This is a standard approach used during rounding in Javascript.

Net result is I don't see anything to fix here.

**Comment by jpmcdonald** [comment]
The bug occurs when you apply an active effect MULTIPLY to a skill EML.  I'm trying to find where this occurs in the code, but I'm not tracking quite how AE's work. Rounding should occur immediately after that application and that should fix this issue.

**Comment by jpmcdonald** [comment]
It may be here, or near here:

 // Apply all changes
        for (let change of changes) {
            change.effect.apply(skill, change);
        }

I'm not sure where the change.efffect.apply function is defined, (it may be part fo the active effects core abilities; when the change type is multiply, and the change is a floating point, the result may not be an integer.

**Comment by scooper4711** [comment]
I think this needs to be re-opened. 
Steps to reproduce:
1. add an AE with a effect of Physical Skill x 0.5
<img width="406" alt="Screen Shot 2021-09-18 at 1 27 00 PM" src="https://user-images.githubusercontent.com/1970249/133906361-838eb5a8-175b-4cad-bff2-860ba9abcf9c.png">
2. Have a Physical skill with a ML of 51
<img width="406" alt="Screen Shot 2021-09-18 at 1 29 02 PM" src="https://user-images.githubusercontent.com/1970249/133906414-9c5de3c9-4502-46d0-8771-157973cdb414.png">

Result: EML of 25.5.
Expected result: EML of 25 or 26.

**Comment by toastygm** [comment]
This has to do with all the special case code around skills I added.  I will reopen this.

**Comment by toastygm** [comment]
fixed.
