### ISSUE TITLE
AE Skill EML modifications do not cap at EML of 95.

### ISSUE THREAD

**Issue by jpmcdonald** [toastygm/HarnMaster-3-FoundryVTT#303]
It appears the AE for Skill EML is added after the EML is reduced to 95 and not before;  I just rolled against a target of 135 with a significant bonus.

**Comment by toastygm** [comment]
Y'know, Min/Max of EML is a funny thing.  The rules stated on SKILLS 2 are clear.  But automated application is not.

Say you have a ML of 110 in Climbing.  So, I could then cap your EML as 95.  The character is descending into a well, which has a very crumbly and unstable wall, so the GM assesses a -20 penalty.  This would result in an effective EML of 95-20=75.

However, I think the real answer would be that the penalties are supposed to apply to the "base eml", and that any **roll** of >95 is a failure.  Any **roll** of <=05 is a success.  So the proper mechanism is to apply this rule, and its limits, during the die roll rather than to the EML.

In that case, the ML of 110 in Climbing would result in an EML of 110-20=90, which I think is more in line with what the rules expect.

In that case, EML as shown on the character sheet can be any number, even >95 or <5, but the success/failure will be adjusted at the time the roll is made.

**Comment by jpmcdonald** [comment]
From (Skills 2): 

"Effective Mastery Level (EML)
In many instances, ML is modified up or down to produce an Effective Mastery Level (EML) before a skill test is made. " 

Minimum: "Unless the GM deems the task impossible, the minimum EML for an open skill is 05" The sidebar adds that for an impossible task, "...an EML of zero is justified."  

Maximum: "If a character's EML is greater than 95 (after any situational modifications) it is considered to be 95 for the purpose of the skill test."  

The min/max function should be the last part applied.  EML as described in the rules only has context with regard to a specific skills test.  So EML should only be calculated prior to a roll/test and the result should be min/maxed only after all other situational (or other) modifiers have been applied.  

The EML that is listed on the character sheet now, is not as defined within the rules, but is a "preliminary EML"  with known modifiers applied (e.g. current PP/UP as applicable).  

So you are correct, that the correct EML in your example should be 90 and not 75.  

I'm fine with the "preliminary EML" in the character sheet, my question was with regard to the target number that is listed in the chat card.  The Effective Target number is not minimized in the example.  I had not tested this, but the success/failure is properly capped, even though the effective target number is not capped at 95.  So this is largely cosmetic. .  

![Screen Shot 2021-09-18 at 12 54 23 PM](https://user-images.githubusercontent.com/24255029/133898005-a8ba53f9-d007-43d4-9ec5-b8e97c586619.png)

**Comment by scooper4711** [comment]
I think the min/max aspect of the rules should be applied at the last possible moment - e.g. "effective target = min(81+50,95)" - which isn't what you should print out because that would look like crap, but that's how it should be calculated.
Perhaps, for a UX point of view, if the Effective Target calculation is > 95, you could add an additional line of:
EML Max: 95
and if it's < 5, then an additional line of:
EML Min: 05

Then have the Roll line as normal.

**Comment by toastygm** [comment]
It was already fixed.  Closing again.

**Comment by toastygm** [comment]
Just to be clear: in the above, the "Effective Target" might say 131, but if you roll >95, it will fail.
