### ISSUE TITLE
404 error downloading font

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#336]
GET https://*myserver*/systems/hm3/fonts/H%C3%A2rn%20Lakise%20Normal.otf net::ERR_ABORTED 404
GET https://*myserver*/systems/hm3/fonts/H%C3%A2rn%20Runic%20Normal.otf net::ERR_ABORTED 404

Using that URL, I get a 404.

**Comment by toastygm** [comment]
This is almost certainly due to you insisting on using non-ascii characters
in the filename of the font.  Why can't you just use "Harn" instead of
"Hârn" in the filename?  Its trying to convert the "â" character to two
character codes: "%C3%A2".

My suggestion is to change the filename so this problem doesn't reoccur.

Tom.

--
*Tom Rodriguez*
*w:* www.casualinsight.com | *e:* ***@***.***
*LinkedIn:* www.linkedin.com/in/tomrodriguez
*Twitter:* @TomRodriguezCI <https://twitter.com/TomRodriguezCI>

**Comment by toastygm** [comment]
Also, please give this issue a better name.  "Error in console" is not a good title for a bug report.  Maybe "Error Downloading Font" or something like that.
