### ISSUE TITLE
Support "50% dodge" defense option for missile weapons

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#342]
One option when defending against missile weapons is to dodge, but with a penalty of "50% Dodge". This defense is when dodging high-velocity missiles.
Since there's no good opportunity to insert a dodge modifier into the attack dialog flow, one option is to offer a "50% dodge" defense option that the player can select.
When that option is selected, the player's dodge EML is reduced by 50% of their ML (note - I'm making an assumption that the penalties for PP is *not* halved. So subtracting 50% of ML will apply the full physical penalty.)

**Comment by toastygm** [comment]
At this point I don't think I am going to implement this.  You can achieve much of this by using Active Effects.  Otherwise, instead of using Automated Combat, use Assisted Combat.  In that case, when performing your Dodge roll, you can specify a particular modifier to the dodge roll (for instance, reducing it by 50%).  These are the ways I would handle this at this time.
