### ISSUE TITLE
New Item Type, Currency

### ISSUE THREAD

**Issue by DustyGold** [toastygm/HarnMaster-3-FoundryVTT#345]
To enhance the use of modules such as Monk's Enhanced Journal and to track different kingdom currency values, add a currency item type that will track all values of currency and allow automatic deductions (much like tracking arrow usage) when items are purchased.

**Comment by jpmcdonald** [comment]
So Monk's Enhanced Journal looks interesting, though heavily D&D focused.  A couple of the items are nice such as the drag and drop check lists and I understand it makes distributing loot easier.  I would probably use the Encounter Entry, but I'm not sure some of the others add that much.  Why do I need a person entry when I already have a character template. Plus the fields are very focused on D&D; e.g. Ideals, Flaws, Bonds, etc. 

Some of what you want is already available within HM3.  I've created coin items which can be used (they just show up in the misc. gear) part of the inventory.  I can dump loot into a Container actor item and just drag and drop.  I can treat it as a shop if I want... Etc.  Pretty easy to track and move stuff.  Just drag and drop.  The question will be where this falls in priority I suppose...

**Comment by toastygm** [comment]
Note that the "Value" field represents the "canonical" currency value, against which everything else is measured.  Think of this as being like the "US Dollar".  So if you state that the value of 1 = Khuzdul 1 silver penny, then a "Golotha Silver Penny" might have a value of 0.75, since the Golothan currency is generally shaved and less pure silver than a Khuzdul penny.  This is just an example, you could choose a value of 1 to be anything you like.

This would allow you to track the various types of currency, and exactly how many of each you have.

Note that purchasing certain goods may have a different price using one currency versus another.  For example, in Rethem a shield may cost 15 Golotha Pennies (with a value of 11.75 Khuzdul pennies), but if you pay in Khuzdul pennies it might be 13 Khuzdul pennies, all because in Rethem the Golotha pennies are preferred.

Anyway, this allows you to be as crazy as you want to be with currency.  Or, for simplicity, just leave value at 1 and assume all pennies are the same everywhere.

Just FYI, this is probably going to be a very low priority for me to support.
