### ISSUE TITLE
Containers will not allow drag and drop.

### ISSUE THREAD

**Issue by greybeardgunner** [toastygm/HarnMaster-3-FoundryVTT#369]
![Capture](https://user-images.githubusercontent.com/77867508/213733687-ca46710f-615d-4da7-9e87-5470090624cf.PNG)

**Comment by toastygm** [comment]
The issue is when something is moved from one actor to another (such as from one character to another character, or a character to a container actor) the move won't happen and it will display the warning: "Error accessing actor where container is coming from, move aborted".

This warning indicates that the current user cannot modify the actor that the item is coming from, because the current user is not an owner for that source actor.  You may have read-only access to see the items, but you don't have write access to remove the item from their inventory.

Normally, the GM shouldn't see this message, since the GM has access to all actors.

**Comment by greybeardgunner** [comment]
Ok...
I am not dragging items from another actor, but from the Items tab in Foundry. I thought perhaps it was a permissions thing as you state, as I had only tried dragging custom made items (created by me) to the container. But when I imported one of the weapons from the compendium to the Items category and tried to drag it into the container, I get the same error.  Do you not get this error when you try to drag an item into a container? If you can't replicate the issue, than it must be on my system. Any ideas what might cause it?

**Comment by KaizenLev** [comment]
Hello! 
If I may add, I happen to have the same exact issue. I only can add items to characters from compendiums. But if I import items from compendium, I can't add them to characters.

**Comment by toastygm** [comment]
Well, I'm embarrassed.  As it turns out, it works on my system because I already fixed it, but forgot to push the fixes.  So I will be pushing the fixes today.
