### ISSUE TITLE
Add Size value to Armor/Clothing items

### ISSUE THREAD

**Issue by mrg67** [toastygm/HarnMaster-3-FoundryVTT#48]
Recommendation:
As per Character 6 sidebar of HM3 rules, add a Size Value to the Armor/Clothing item sheet.

![image](https://user-images.githubusercontent.com/74210758/99192602-834d7a00-2728-11eb-9a47-e13373bd6dda.png)

![image](https://user-images.githubusercontent.com/74210758/99192629-9fe9b200-2728-11eb-8e82-0ead689438d1.png)

**Comment by toastygm** [comment]
I have added the size to the armor items.

Note that this required modifying the data model to add the size field, so it is going to require a migration in the next version.

**Comment by mrg67** [comment]
Just curious...what all is involved in a "migration?"

**Comment by toastygm** [comment]
In FVTT, each actor has a data model associated with it.  The data model has whatever fields you define: for instance, each of the abilities, endurance, etc.  Items also have a datamodel, such as quantity, weight, notes, etc.  The system expects all items of a particular type to have all of the elements of the data model.  So if I change armor items to have a new element "size", then all of the armor items already out there don't have that element, and the code will break.  So, I have to write special code that on startup detects whether the character is from an older version, and then perform the upgrade (e.g., adding a new property for size).  Otherwise, I would have to force everyone to delete their old characters and recreate them from scratch every time I changed the data model.  It is extra work to write this migration code, and there is always the chance that I mess up and break people's characters.  Not something I like risking, especially unless it is for a compelling reason.

**Comment by mrg67** [comment]
Ah, I get it now.  Appreciate the explanation.
