### ISSUE TITLE
For spells, when rolling, include the description

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#64]
Include the spell description when rolling a spell.
Options include:

 - display the text, the whole text, and nothing but the text
 - display the description as hover text somewhere.

This will allow players and gms who don't have the spells memorized to have a quick reference to what it does.

**Comment by toastygm** [comment]
For spells/Invocations/Psionics, we have two alternatives: Notes and Description.  Notes are meant to be brief, one-liner sorts of things; I would go so far as to say 50 characters or less would be reasonable.  Description is rich text, containing markup and as much length as you like.

In the small confines of a chat entry, dumping the full description would almost certainly be overwhelming.  I could limit it to the first 256 characters or so arbitrarily, but I can't see just dumping the whole description into this field.  Also note that since it is rich text, it can include such things as tables, embedded pictures, etc.  This will certainly not come across in the chat box, and may make the description in the chat box unintelligible.

Thoughts?

**Comment by jpmcdonald** [comment]
I recommend displaying just the note field.

**Comment by scooper4711** [comment]
Yes, then the player can decide how much of the description to include there. A reasonable compromise.

**Comment by toastygm** [comment]
Fixed in 0.7.5
