### ISSUE TITLE
Calculate Move

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#79]
Move is your agility * 5 - PP * 5
Currently, Move is a static value you input.

**Comment by scooper4711** [comment]
Looks like you input move and it subtracts your PP for "effective move".
Would be nice to have it measured in ft and as you move in the game, the movement is subtracted from your "effective move".

**Comment by toastygm** [comment]
That is a "normal" value, for humans.  This value varies widely depending on species.

Since the "character" sheet can be used for more than just humans (e.g., Gargun and even some Ivashu), I did not want to make the assumption that the move rate would be AGL*5.  If you're human, its easy enough to do the calculation yourself, set it once, and forget about it.
