### ISSUE TITLE
Hand modifier not included in AML calculation

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#91]
bastard sword, when used one-handed, has a Hand modifier of -10.
When that is entered (or dragged from the Std Weapons), it shows up in the combat table as 'x'.
I copied the sword, renamed it with 2-handed in the name and removed the Hand modifier. The AMLs are the same.
So it doesn't look like the AML is subtracting the hand modifier.
I put in a positive hand modifier, and it had no impact on AML.

**Comment by toastygm** [comment]
I don't calculate the hand modifier.  That's because I have no idea whether the character is using it single-headed or two-handed.  I provided it as more of a text item, but it has no effect.

The easiest thing is to just enter the modifier value when performing the attack.

Otherwise, when you swing a weapon with a hand mode modifier I will have to additionally ask whether you are using it single- or two-handed.  I dislike having to add yet another question to the attack dialog.

**Comment by scooper4711** [comment]
Naw - one handed is one weapon with a modifier, two handed is a different weapon with zero weight without the modifier. 
Your idea of removing the "hand" word and making it a generic modifier (mundane, magic or otherwise) works well.
